name = "OscarPuiseuxPolynomial"
uuid = "7e8d91a7-ef99-4171-8ecc-0b23a9b9da6d"
version = "1.0.0-DEV"
authors = ["Oliver Clarke <oliver.clarke.crgs@gmail.com>"]

[deps]
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
Oscar = "1.6.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
